"""create initial reporting schema

Revision ID: 0e430c95a282
Revises: 
Create Date: 2026-07-20 00:47:02.731382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e430c95a282'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('POWER_OUTAGE', 'LOW_VOLTAGE', 'HIGH_VOLTAGE', 'TRANSFORMER_FAULT', 'FALLEN_CABLE', 'METER_ISSUE', 'STREETLIGHT_FAULT', 'OTHER', name='report_type', native_enum=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'VALIDATED', 'REJECTED', 'RESOLVED', name='report_status', native_enum=False), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.CheckConstraint(
        "confidence_score >= 0 AND confidence_score <= 1",
        name="ck_reports_confidence_score",
    ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
    "ix_reports_status",
    "reports",
    ["status"],
    )

    op.create_index(
        "ix_reports_report_type",
        "reports",
        ["report_type"],
    )

    op.create_index(
        "ix_reports_submitted_at",
        "reports",
        ["submitted_at"],
    )

    op.create_index(
        "ix_reports_reporter_id",
        "reports",
        ["reporter_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        "ix_reports_reporter_id",
        table_name="reports",
    )

    op.drop_index(
        "ix_reports_submitted_at",
        table_name="reports",
    )

    op.drop_index(
        "ix_reports_report_type",
        table_name="reports",
    )

    op.drop_index(
        "ix_reports_status",
        table_name="reports",
    )

    op.drop_table("reports")
