"""add state lga landmark reporter_phone to reports

Revision ID: f2b0f6df5a72
Revises: 8c230dad8264
Create Date: 2026-07-30 00:28:47.759821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b0f6df5a72'
down_revision: Union[str, None] = 'b6f7e00b9187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('state', sa.String(length=100), nullable=True))
    op.drop_column('reports', 'sstate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('sstate', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('reports', 'state')
    # ### end Alembic commands ###
